// <auto-generated />
namespace ExamAppMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedsurnamefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedsurnamefield));
        
        string IMigrationMetadata.Id
        {
            get { return "202104160831286_added surname field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
